targets:
  $default:
    builders:
      drift_dev:
        options:
          skip_verification: true
          generate_connect_constructor: true
          write_from_json_string_constructor: true
          named_parameters: true
          apply_converters_on_variables: true
